# Base URL
baseurl:

# Harmony theme configuration. Please change accordingly.
harmony:
  # Little description about your site
  meta_description: Armin's blog
  basetheme: theme-base-01

  # Google Analytics key, leave blank to ignore
  google_analytics_key: 

  # Profile links, leave blank to ignore
  social: 
    github: arminc
    twitter: acoralic
    gplus: +103823895018150177843

# Conversion / Build settings 
markdown:    kramdown
highlighter: pygments # this is how you put pygments config in jekyll 2.0 instead of pygments: true

# Permalinks
permalink: /:title/

exclude: 
  - CNAME
  - Gemfile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock
  - arminc.sublime-project

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed
